name: Trivy docker image scan

on:
  workflow_run:
    workflows: ["Docker Image CI application"]
    types:
      - completed
  workflow_dispatch:
    
permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read 
      security-events: write 
      actions: read 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: '${{ vars.TEST_REPOSITORY }}/armadillo-app:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

